### ISSUE TITLE
Selection is not active in export

### ISSUE THREAD

**Issue by ponceta** [QGEP/qgepqwat2ili#42] opened 2021-09-01 11:47 UTC
![image](https://user-images.githubusercontent.com/8614223/131665486-1bb496c5-5eed-4ba1-b4f1-0cd0004f2c6e.png)

**Comment by ponceta** [comment] 2021-09-01 11:48
2021-09-01T13:39:47     WARNING    Traceback (most recent call last):
              File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\dbconnector\pg_connector.py", line 43, in __init__
              self.conn = psycopg2.connect(uri)
              File "C:\Users\pulpoar\AppData\Roaming\Python\Python39\site-packages\psycopg2\__init__.py", line 122, in connect
              conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
             psycopg2.OperationalError: could not connect to server: Connection refused (0x0000274D/10061)
              Is the server running on host "localhost" (::1) and accepting
              TCP/IP connections on port 5432?
             could not connect to server: Connection refused (0x0000274D/10061)
              Is the server running on host "localhost" (127.0.0.1) and accepting
              TCP/IP connections on port 5432?
             
             
             During handling of the above exception, another exception occurred:
             
             Traceback (most recent call last):
              File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\gui\panel\dataset_selector.py", line 132, in set_current_layer
              db_factory.get_db_connector(
              File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\db_factory\pg_factory.py", line 34, in get_db_connector
              return PGConnector(uri, schema)
              File "C:\Users/pulpoar/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QgisModelBaker\libqgsprojectgen\dbconnector\pg_connector.py", line 45, in __init__
              raise DBConnectorError(str(e), e)
             QgisModelBaker.libqgsprojectgen.dbconnector.db_connector.DBConnectorError: could not connect to server: Connection refused (0x0000274D/10061)
              Is the server running on host "localhost" (::1) and accepting
              TCP/IP connections on port 5432?
             could not connect to server: Connection refused (0x0000274D/10061)
              Is the server running on host "localhost" (127.0.0.1) and accepting
              TCP/IP connections on port 5432?

**Comment by ponceta** [comment] 2021-09-01 11:58
Probably due to the fact that we don't use a pg_service

**Comment by olivierdalang** [comment] 2021-09-01 13:58
Is that the full trace (full log) ? (asking as I don't see any code from the qgep plugin in the trace)

When exactly does the exception happen (when you click on "OK" in the export dialog, or before that when you open the dialog) ?

Could you paste what you see in the information panel in the layer properties window (of the reach layer) under "source" ? (obviously obfuscating passwords or login info if any) 

Thanks !

**Comment by sjib** [comment] 2021-09-01 14:18
I guess this is do to that you can only export pg_qgep with the plugin currently.

I was now successful to export a selection (of reaches): https://github.com/QGEP/qgepqwat2ili/issues/38#issuecomment-910329245
It also selects the connected structures and VSA-KEK data.

**Comment by olivierdalang** [comment] 2021-09-02 10:33
> I guess this is do to that you can only export pg_qgep with the plugin currently.

Yes I think that's the root cause. How do we want to deal with that ?

So far I thought the the QGEP way to configure connections was with services.

Supporting other connection types is of course possible, but there are potentially many cases to support (.pgpassword, qgis encrypted configs, maybe more ?), hence more work and more maintenance burden. Note that we must be able to retrieve the full connection info, incl. unencrypted password, as we need to provide those to ili2pg.

**Comment by sjib** [comment] 2021-09-02 11:40
I would be happy to have an option to choose another service (or is that not a service?) than the one default that is set in the plugin
https://github.com/QGEP/qgepqwat2ili/blob/master/qgepqwat2ili/config.py#L17 and https://github.com/QGEP/qgepqwat2ili/blob/master/qgepqwat2ili/config.py#L23

Technically I do not know what you have to add to make sure that the service fits with the layer you make a selection of. Or what other hurdles their are to implement this. We have already a discussion on this here: https://github.com/QGEP/qgepqwat2ili/issues/39

Any other user needs @ponceta @urskaufmann @varrieta @TriformMoritz @tproduit @DflGruBoe @kandre @max-trolliet @PeterZamudio ?

**Comment by olivierdalang** [comment] 2021-09-15 08:08
Closing this as it is a duplicate of #39

**Closed by olivierdalang** 2021-09-15 08:08 UTC
Labels: bug
